@@startuml

entity user {
    id
    --
    name
}


entity channel {
    id
    --
    name
    work_space_id
}

entity workspace {
    id
    --
    name
}

entity message {
    id
    --
    sender_id (FK)
    channel_id (FK)
    message_body
    created_at
    modified_at
    parent_message_id
}

entity channel_member {
    id
    --
    channel_id (FK)
    user_id (FK)
}

entity channel_workspace_relation {
    id
    --
    channel_id (FK)
    workspace_id (FK)
}

entity workspace_member {
    id
    --
    workspace_id (FK)
    user_id (FK)
}

user ||-l-o{ message
user ||--o{ channel_member
user ||-r-o{ workspace_member
channel ||-r-o{ channel_member
channel ||-u-o{ message
channel ||--o{ channel_workspace_relation
workspace ||-l-o{ channel_workspace_relation
workspace ||-u-o| workspace_member

@@enduml