@@startuml

entity user {
    id
    --
    name
}


entity channel {
    id
    --
    name
    work_space_id
}

entity workspace {
    id
    --
    name
}

entity message {
    id
    --
    sender_id (FK)
    channel_id (FK)
    message_body
    created_at
    modified_at
    parent_message_id
}

entity channel_user {
    id
    --
    channel_id (FK)
    user_id (FK)
}


entity workspace_user {
    id
    --
    workspace_id (FK)
    user_id (FK)
}

user ||-l-o{ message
user ||--o{ channel_user
user ||-r-o{ workspace_user
channel ||-r-o{ channel_user
channel ||-u-o{ message
workspace ||-u-o| workspace_user

@@enduml