@startuml
entity single_menu{
    id
    --
    name
    single_menu_genre_id (FK)
    single_menu_price_id (FK)
    can_take_out
}

entity single_menu_genre {
    id
    --
    genre
}

entity single_menu_price {
    id
    --
    single_menu_id (FK)
    price
    start_date
    end_date
}

entity set_menu{
    id
    --
    name 
    set_menu_genre_id (FK)
    set_menu_price_id (FK)
}

entity set_menu_genre {
    id
    --
    genre
}

entity set_menu_price {
    id
    --
    set_menu_id (FK)
    price
    start_date
    end_date
}

entity order{
    id
    --
    customer_name
    customer_phone_number
    is_paid
    ordered_at
    note
}

entity single_menu_order{
    id
    --
    order_id（FK）
    single_menu_id (FK)
    quantity
    is_sabinuki
    rice_size_id
}

entity set_menu_order{
    id
    --
    order_id（FK）
    set_menu_id (FK)
    quantity
    is_sabinuki
    rice_size_id
}

entity rice_size{
    id
    --
    name
}

entity set_single_relation {
    id
    --
    set_menu_id (FK)
    single_menu_id (FK)
}

single_menu }|--|| single_menu_genre
single_menu ||--|| single_menu_price
single_menu ||--o{ single_menu_order
set_menu }|--|| set_menu_genre
set_menu ||--|| set_menu_price
set_menu ||--o{ set_menu_order
order ||--o{ single_menu_order
order ||--o{ set_menu_order
single_menu_order }o--o| rice_size
set_menu_order }o--o| rice_size
set_single_relation }o--|| set_menu
set_single_relation }o--|| single_menu

@enduml