@@@startuml

hide Circle

entity User {
    id
    --
    name
    team_id
    team_name
    access_token
}

entity Message {
    id
    --
    body
    sender_id (FK)
    recipient_id (FK)
    channel_id
}
note right: sender_idはUser.idを参照\nrecipient_idはRecipient.idを参照

entity Recipient {
    message_id (FK)
    user_id (FK)
    --
}

entity Reminder {
    id
    --
    message_id (FK)
    reminder_frequency_id (FK)
    reminder_frequency_value
    next_remind_date
    completed_at
}

entity ReminderFrequency {
    id
    --
    name
}

User ||--o{ Message
Message ||--|{ Recipient
User ||--|{ Recipient
Reminder ||--|| Message
Reminder }|--|| ReminderFrequency

@@@enduml