@@startuml

hide Circle

entity Document {
    id
    --
    name
    body
    order
    directory_id (FK)
    create_user_id (FK)
    last_modify_user_id (FK)
    created_at
    last_modified_at
}

entity DocumentHistory {
    id
    --
    document_id (FK)
    name
    body
    modify_user_id (FK)
    modified_at
}
note right: 変更されるごとに\nレコードが作成される

entity Directory {
    id
    --
    name
    create_user_id (FK)
    modify_user_id (FK)
    created_at
    modified_at
}

entity DirectoryClosure {
    id
    --
    parent_id (FK)
    child_id (FK)
}
note right: 閉包テーブル\nディレクトリの親子関係をすべて記録する 

entity User {
    id
    --
    name
}

Document ||--o{ DocumentHistory
Document }|--|| Directory
Document }o--|{ User
Directory }|--|{ DirectoryClosure
DocumentHistory }o-l-|{ User


@@enduml